// Traductions pour le système de gestion d'entraînement sportif
const translations = {
    ar: {
        pageTitle: "نظام إدارة التدريب الرياضي",
        appTitle: "نظام إدارة التدريب",
        home: "الرئيسية",
        login: "تسجيل الدخول",
        about: "معلومات حول الموقع",
        contact: "اتصل بنا",
        userIdDisplay: "معرف المستخدم",
        userIdNotAvailable: "معرف المستخدم: غير متاح",
        welcomeTitle: "مرحبًا بك في نظام إدارة التدريب الرياضي",
        welcomeText: "أدوات متقدمة للمدربين لإنشاء برامج تدريبية مخصصة في كرة القدم.",
        getStarted: "ابدأ الآن",
        authModalTitle: "تسجيل الدخول / التسجيل",
        emailLabel: "البريد الإلكتروني:",
        emailPlaceholder: "أدخل بريدك الإلكتروني",
        passwordLabel: "كلمة المرور:",
        passwordPlaceholder: "أدخل كلمة المرور",
        loginButton: "تسجيل الدخول",
        registerButton: "تسجيل جديد",
        logoutButton: "تسجيل الخروج",
        loginSuccess: "تم تسجيل الدخول بنجاح!",
        registerSuccess: "تم التسجيل بنجاح! يمكنك الآن تسجيل الدخول.",
        logoutSuccess: "تم تسجيل الخروج بنجاح.",
        loginError: "خطأ في تسجيل الدخول:",
        registerError: "خطأ في التسجيل:",
        logoutError: "خطأ في تسجيل الخروج:",
        coachProfileTitle: "إدارة ملف المدرب",
        nameLabel: "الاسم:",
        namePlaceholder: "اسم المدرب",
        ageLabel: "العمر:",
        agePlaceholder: "عمر المدرب",
        nationalityLabel: "الجنسية:",
        nationalityPlaceholder: "جنسية المدرب",
        phoneLabel: "رقم الهاتف:",
        phonePlaceholder: "رقم هاتف المدرب",
        coachLevelLabel: "المستوى التدريبي:",
        selectLevel: "اختر المستوى",
        saveCoachProfile: "حفظ بيانات المدرب",
        saveCoachProfileSuccess: "تم حفظ بيانات المدرب بنجاح!",
        saveCoachProfileError: "حدث خطأ أثناء حفظ بيانات المدرب.",
        loginRequired: "يرجى تسجيل الدخول أولاً لحفظ البيانات.",
        ageGroupTitle: "اختيار الفئة العمرية",
        u15: "أقل من 15",
        u17: "أقل من 17",
        u19: "أقل من 19",
        women: "الفريق النسائي",
        seniors: "الأكابر",
        ageGroupInstructionsTitle: "تعليمات الفئة العمرية:",
        ageGroupU15Instruction: "تعليمات خاصة بالفئة العمرية أقل من 15 سنة: التركيز على الأساسيات وتطوير المهارات الفردية.",
        ageGroupU17Instruction: "تعليمات خاصة بالفئة العمرية أقل من 17 سنة: تطوير الجوانب التكتيكية والفهم الجماعي.",
        ageGroupU19Instruction: "تعليمات خاصة بالفئة العمرية أقل من 19 سنة: التركيز على اللياقة البدنية والتحمل، وصقل المهارات المتقدمة.",
        ageGroupWomenInstruction: "تعليمات خاصة بالفريق النسائي: برامج تدريبية مصممة لتناسب الاحتياجات البدنية والتكتيكية للاعبات.",
        ageGroupSeniorsInstruction: "تعليمات خاصة بفئة الأكابر: برامج تدريبية عالية المستوى، تركز على الأداء التنافسي والتكتيكات المعقدة.",
        saveAgeGroup: "حفظ الفئة العمرية",
        saveAgeGroupSuccess: "تم حفظ الفئة العمرية:",
        saveAgeGroupError: "حدث خطأ أثناء حفظ الفئة العمرية.",
        selectAgeGroupFirst: "يرجى اختيار فئة عمرية أولاً.",
        scheduleManagementTitle: "إدارة جدولة التدريب والمباريات",
        selectDay: "اختر اليوم",
        trainingTimePlaceholder: "وقت التدريب",
        matchTimePlaceholder: "وقت المباراة",
        addDaySchedule: "إضافة يوم للجدول",
        saveSchedule: "حفظ الجدول",
        saveScheduleSuccess: "تم حفظ الجدول بنجاح!",
        saveScheduleError: "حدث خطأ أثناء حفظ الجدول.",
        playingPhilosophyTitle: "اختيار فلسفة اللعب",
        offensive: "هجومية",
        defensive: "دفاعية",
        possession: "الاستحواذ",
        formationbased: "حسب التشكيلة",
        selectedPhilosophy: "فلسفة اللعب المختارة:",
        playerManagementTitle: "إدارة اللاعبين",
        playerNameLabel: "اسم اللاعب:",
        playerNamePlaceholder: "اسم اللاعب",
        skillCharacteristics: "الخصائص المهارية",
        passing: "التمرير:",
        receiving: "الاستقبال:",
        dribblingrun: "الجري بالكرة:",
        dribblingskill: "المراوغة:",
        heading: "الضرب بالرأس:",
        shooting: "التسديد:",
        longpassing: "التمريرات الطويلة الدقيقة:",
        ballcontrol: "التحكم بالكرة:",
        twofooted: "اللعب بالرجلين:",
        finishingpressure: "التهديف في المساحات الضيقة:",
        physicalAbilities: "الخصائص البدنية",
        stamina: "التحمل البدني:",
        fitness: "اللياقة البدنية:",
        physique: "البنية الجسمانية:",
        speed: "السرعة:",
        strength: "القوة البدنية:",
        balanceagility: "التوازن والرشاقة:",
        tacticalUnderstanding: "الخصائص التكتيكية",
        gameintelligence: "الذكاء بالكرة أو بدونها:",
        coachinstructions: "تطبيق تعليمات المدرب:",
        defensiveaggression: "الشراسة الدفاعية:",
        offensivecontribution: "الغزارة الهجومية:",
        positioning: "التمركز الصحيح:",
        readinggame: "قراءة اللعب:",
        teamworkpressing: "التنظيم والضغط الجماعي:",
        mentalPsychologicalTraits: "الخصائص الذهنية والنفسية",
        mentaltoughness: "الجانب الذهني:",
        psychologicalstability: "الجانب النفسي:",
        concentration: "التركيز:",
        selfconfidence: "الثقة بالنفس:",
        leadership: "القيادة:",
        handlingpressure: "القدرة على التعامل مع الضغط:",
        motivationcompetitiveness: "الحافز والرغبة في الفوز:",
        addEditPlayer: "إضافة / تعديل لاعب",
        addPlayerSuccess: "تم إضافة اللاعب بنجاح!",
        editPlayerSuccess: "تم تعديل بيانات اللاعب بنجاح!",
        savePlayerError: "حدث خطأ أثناء حفظ بيانات اللاعب.",
        playerNameRequired: "يرجى إدخال اسم اللاعب.",
        playersList: "قائمة اللاعبين",
        tablePlayerName: "الاسم",
        tableSkillAvg: "المهارة (متوسط)",
        tablePhysicalAvg: "البدنية (متوسط)",
        tableTacticalAvg: "التكتيكية (متوسط)",
        tableMentalAvg: "الذهنية (متوسط)",
        tableActions: "الإجراءات",
        edit: "تعديل",
        delete: "حذف",
        confirmDeletePlayer: "هل أنت متأكد أنك تريد حذف هذا اللاعب؟",
        deletePlayerSuccess: "تم حذف اللاعب بنجاح!",
        deletePlayerError: "حدث خطأ أثناء حذف اللاعب.",
        teamAnalysisTitle: "تحليل الفريق وإنشاء الخطط",
        analyzeTeam: "تحليل الفريق",
        noPlayersToAnalyze: "لا يوجد لاعبون لتحليلهم. يرجى إضافة لاعبين أولاً.",
        individualPlayerAnalysis: "تحليل اللاعبين الفردي",
        playerType: "النوع:",
        skillAvg: "متوسط المهارة:",
        physicalAvg: "متوسط البدنية:",
        tacticalAvg: "متوسط التكتيكية:",
        mentalAvg: "متوسط الذهنية:",
        playerTypeSkillful: "مهاري",
        playerTypePhysical: "بدني",
        playerTypeTactical: "تكتيكي",
        playerTypeMental: "ذهني",
        playerTypeGeneral: "عام",
        teamCollectiveAnalysis: "تحليل الفريق الجماعي",
        categoryAverages: "متوسطات الفئات",
        teamOverallAverages: "متوسطات الخصائص الكلية",
        categorySkill: "المهارية",
        categoryPhysical: "البدنية",
        categoryTactical: "التكتيكية",
        categoryMental: "الذهنية",
        overallTeamAverage: "متوسط التقييم الكلي للفريق:",
        suggestedFormations: "التشكيلات المقترحة ونقاط القوة والضعف",
        noFormationSuggestion: "لا توجد تشكيلة مقترحة حاليًا.",
        noStrengthsWeaknesses: "لا توجد نقاط قوة وضعف محددة حاليًا.",
        formationOffensive: "بناءً على فلسفتك الهجومية ومتوسط المهارات العالي، قد تكون تشكيلة 4-3-3 أو 4-2-3-1 مناسبة.",
        strengthsOffensive: "نقاط القوة: القدرة على بناء اللعب الهجومي، المهارات الفردية العالية، والضغط المتقدم.",
        weaknessesOffensive: "نقاط الضعف المحتملة: قد تكون هناك مساحات خلف خط الدفاع، والحاجة إلى توازن دفاعي.",
        formationDefensive: "بناءً على فلسفتك الدفاعية ومتوسط القدرات البدنية الجيدة، قد تكون تشكيلة 4-4-2 أو 5-3-2 مناسبة.",
        strengthsDefensive: "نقاط القوة: التنظيم الدفاعي القوي، القدرة على التحمل البدني، والصلابة الدفاعية.",
        weaknessesDefensive: "نقاط الضعف المحتملة: قد تواجه صعوبة في الانتقال للهجوم السريع، والحاجة إلى لاعبين مبدعين في الأمام.",
        formationPossession: "بناءً على فلسفتك الاستحواذية ومتوسط الفهم التكتيكي الجيد، قد تكون تشكيلة 4-3-3 أو 4-1-4-1 مناسبة.",
        strengthsPossession: "نقاط القوة: التحكم بالكرة، بناء اللعب من الخلف، والقدرة على فرض الإيقاع.",
        weaknessesPossession: "نقاط الضعف المحتملة: قد تكون عرضة للهجمات المرتدة السريعة، والحاجة إلى تركيز عالٍ طوال المباراة.",
        formationFormationBased: "اخترت فلسفة تعتمد على التشكيلة. يرجى تحديد التشكيلة المفضلة لديك لتحليل أعمق.",
        strengthsFormationBased: "نقاط القوة: المرونة التكتيكية والقدرة على التكيف مع الخصوم.",
        weaknessesFormationBased: "نقاط الضعف المحتملة: قد يتطلب الأمر وقتًا أطول للاعبين للتكيف مع التغييرات المتكررة في التشكيلة.",
        formationGeneral: "لا توجد تشكيلة مقترحة محددة حاليًا. يمكننا تحليل أعمق بعد اختيار فلسفة اللعب وتوفر بيانات كافية عن اللاعبين.",
        strengthsGeneral: "نقاط القوة: تعتمد على متوسط قدرات الفريق.",
        weaknessesGeneral: "نقاط الضعف: تعتمد على متوسط قدرات الفريق.",
        programGenerationTitle: "إنشاء البرامج التدريبية",
        annualProgram: "برنامج سنوي",
        monthlyProgram: "برنامج شهري",
        weeklyProgram: "برنامج أسبوعي",
        physicalProgram: "برنامج تحضير بدني",
        programOutputPlaceholder: "سيظهر البرنامج التدريبي الذي تم إنشاؤه هنا.",
        generatingProgram: "جاري إنشاء البرنامج...",
        programGenerationError: "تعذر إنشاء البرنامج التدريبي. يرجى المحاولة مرة أخرى.",
        apiConnectionError: "حدث خطأ أثناء الاتصال بالنموذج:",
        printProgram: "طباعة البرنامج (PDF)",
        printPdfNotAvailable: "وظيفة طباعة PDF قيد التطوير. يمكنك نسخ النص يدويًا.",
        aboutTitle: "معلومات حول الموقع",
        aboutText1: "هذا الموقع هو نظام شامل لإدارة التدريب الرياضي في كرة القدم، مصمم خصيصًا للمدربين. يوفر أدوات متقدمة لإنشاء برامج تدريبية مخصصة تتناسب مع احتياجات الفريق وأسلوب التدريب المفضل. هدفنا هو تبسيط عملية التخطيط والتحليل، ومساعدة المدربين على تحقيق أقصى إمكانات لاعبيهم وفرقهم.",
        aboutText2: "يشمل الموقع ميزات مثل إدارة ملف المدرب، واختيار الفئات العمرية، وجدولة التدريبات والمباريات، وتحديد فلسفة اللعب، وإدارة شاملة للاعبين مع تقييمات تفصيلية للمهارات البدنية، التكتيكية، والذهنية. كما يوفر تحليلاً متقدمًا للفريق واقتراحات للخطط، بالإضافة إلى إمكانية إنشاء برامج تدريبية متنوعة وطباعتها.",
        contactTitle: "اتصل بنا",
        yourNameLabel: "اسمك:",
        yourNamePlaceholder: "اسمك الكامل",
        yourEmailLabel: "بريدك الإلكتروني:",
        yourEmailPlaceholder: "example@example.com",
        yourMessageLabel: "رسالتك:",
        yourMessagePlaceholder: "اكتب رسالتك هنا...",
        sendMessage: "إرسال الرسالة",
        footerText: "© 2025 نظام إدارة التدريب الرياضي. جميع الحقوق محفوظة.",
        sunday: "الأحد",
        monday: "الاثنين",
        tuesday: "الثلاثاء",
        wednesday: "الأربعاء",
        thursday: "الخميس",
        friday: "الجمعة",
        saturday: "السبت",
        programFocusAnnual: "تخطيط شامل للموسم، تقسيم الفترات (تحضير، منافسة، انتقالية)، والأهداف الرئيسية لكل فترة.",
        programFocusMonthly: "أهداف تدريبية محددة للشهر، تمارين مفصلة، وتقييم التقدم.",
        programFocusWeekly: "جدول يومي للتدريبات، تمارين محددة، وتوزيع الأحمال التدريبية.",
        programFocusPhysical: "برنامج تحضير بدني شامل يركز على تطوير القوة، السرعة، التحمل، والمرونة."
    },
    
    en: {
        pageTitle: "Sports Training Management System",
        appTitle: "Training Management System",
        home: "Home",
        login: "Login",
        about: "About",
        contact: "Contact Us",
        userIdDisplay: "User ID",
        userIdNotAvailable: "User ID: Not Available",
        welcomeTitle: "Welcome to the Sports Training Management System",
        welcomeText: "Advanced tools for coaches to create customized training programs in football.",
        getStarted: "Get Started",
        authModalTitle: "Login / Register",
        emailLabel: "Email:",
        emailPlaceholder: "Enter your email",
        passwordLabel: "Password:",
        passwordPlaceholder: "Enter your password",
        loginButton: "Login",
        registerButton: "Register",
        logoutButton: "Logout",
        loginSuccess: "Login successful!",
        registerSuccess: "Registration successful! You can now log in.",
        logoutSuccess: "Logout successful.",
        loginError: "Login error:",
        registerError: "Registration error:",
        logoutError: "Logout error:",
        coachProfileTitle: "Coach Profile Management",
        nameLabel: "Name:",
        namePlaceholder: "Coach name",
        ageLabel: "Age:",
        agePlaceholder: "Coach age",
        nationalityLabel: "Nationality:",
        nationalityPlaceholder: "Coach nationality",
        phoneLabel: "Phone Number:",
        phonePlaceholder: "Coach phone number",
        coachLevelLabel: "Coaching Level:",
        selectLevel: "Select Level",
        saveCoachProfile: "Save Coach Profile",
        saveCoachProfileSuccess: "Coach profile saved successfully!",
        saveCoachProfileError: "Error occurred while saving coach profile.",
        loginRequired: "Please log in first to save data.",
        ageGroupTitle: "Age Group Selection",
        u15: "Under 15",
        u17: "Under 17",
        u19: "Under 19",
        women: "Women's Team",
        seniors: "Seniors",
        ageGroupInstructionsTitle: "Age Group Instructions:",
        ageGroupU15Instruction: "Instructions for Under 15 age group: Focus on fundamentals and developing individual skills.",
        ageGroupU17Instruction: "Instructions for Under 17 age group: Develop tactical aspects and team understanding.",
        ageGroupU19Instruction: "Instructions for Under 19 age group: Focus on physical fitness and endurance, refining advanced skills.",
        ageGroupWomenInstruction: "Instructions for Women's Team: Training programs designed to suit the physical and tactical needs of female players.",
        ageGroupSeniorsInstruction: "Instructions for Seniors: High-level training programs focusing on competitive performance and complex tactics.",
        saveAgeGroup: "Save Age Group",
        saveAgeGroupSuccess: "Age group saved:",
        saveAgeGroupError: "Error occurred while saving age group.",
        selectAgeGroupFirst: "Please select an age group first.",
        scheduleManagementTitle: "Training and Match Schedule Management",
        selectDay: "Select Day",
        trainingTimePlaceholder: "Training time",
        matchTimePlaceholder: "Match time",
        addDaySchedule: "Add Day to Schedule",
        saveSchedule: "Save Schedule",
        saveScheduleSuccess: "Schedule saved successfully!",
        saveScheduleError: "Error occurred while saving schedule.",
        playingPhilosophyTitle: "Playing Philosophy Selection",
        offensive: "Offensive",
        defensive: "Defensive",
        possession: "Possession",
        formationbased: "Formation-based",
        selectedPhilosophy: "Selected Playing Philosophy:",
        playerManagementTitle: "Player Management",
        playerNameLabel: "Player Name:",
        playerNamePlaceholder: "Player name",
        skillCharacteristics: "Skill Characteristics",
        passing: "Passing:",
        receiving: "Receiving:",
        dribblingrun: "Dribbling Run:",
        dribblingskill: "Dribbling Skill:",
        heading: "Heading:",
        shooting: "Shooting:",
        longpassing: "Long Passing:",
        ballcontrol: "Ball Control:",
        twofooted: "Two-footed:",
        finishingpressure: "Finishing Under Pressure:",
        physicalAbilities: "Physical Abilities",
        stamina: "Stamina:",
        fitness: "Fitness:",
        physique: "Physique:",
        speed: "Speed:",
        strength: "Strength:",
        balanceagility: "Balance & Agility:",
        tacticalUnderstanding: "Tactical Understanding",
        gameintelligence: "Game Intelligence:",
        coachinstructions: "Following Coach Instructions:",
        defensiveaggression: "Defensive Aggression:",
        offensivecontribution: "Offensive Contribution:",
        positioning: "Positioning:",
        readinggame: "Reading the Game:",
        teamworkpressing: "Teamwork & Pressing:",
        mentalPsychologicalTraits: "Mental & Psychological Traits",
        mentaltoughness: "Mental Toughness:",
        psychologicalstability: "Psychological Stability:",
        concentration: "Concentration:",
        selfconfidence: "Self-confidence:",
        leadership: "Leadership:",
        handlingpressure: "Handling Pressure:",
        motivationcompetitiveness: "Motivation & Competitiveness:",
        addEditPlayer: "Add / Edit Player",
        addPlayerSuccess: "Player added successfully!",
        editPlayerSuccess: "Player data updated successfully!",
        savePlayerError: "Error occurred while saving player data.",
        playerNameRequired: "Please enter player name.",
        playersList: "Players List",
        tablePlayerName: "Name",
        tableSkillAvg: "Skill (Average)",
        tablePhysicalAvg: "Physical (Average)",
        tableTacticalAvg: "Tactical (Average)",
        tableMentalAvg: "Mental (Average)",
        tableActions: "Actions",
        edit: "Edit",
        delete: "Delete",
        confirmDeletePlayer: "Are you sure you want to delete this player?",
        deletePlayerSuccess: "Player deleted successfully!",
        deletePlayerError: "Error occurred while deleting player.",
        teamAnalysisTitle: "Team Analysis and Plan Creation",
        analyzeTeam: "Analyze Team",
        noPlayersToAnalyze: "No players to analyze. Please add players first.",
        individualPlayerAnalysis: "Individual Player Analysis",
        playerType: "Type:",
        skillAvg: "Skill Average:",
        physicalAvg: "Physical Average:",
        tacticalAvg: "Tactical Average:",
        mentalAvg: "Mental Average:",
        playerTypeSkillful: "Skillful",
        playerTypePhysical: "Physical",
        playerTypeTactical: "Tactical",
        playerTypeMental: "Mental",
        playerTypeGeneral: "General",
        teamCollectiveAnalysis: "Team Collective Analysis",
        categoryAverages: "Category Averages",
        teamOverallAverages: "Team Overall Averages",
        categorySkill: "Skill",
        categoryPhysical: "Physical",
        categoryTactical: "Tactical",
        categoryMental: "Mental",
        overallTeamAverage: "Overall Team Average:",
        suggestedFormations: "Suggested Formations and Strengths/Weaknesses",
        noFormationSuggestion: "No formation suggestion currently available.",
        noStrengthsWeaknesses: "No specific strengths and weaknesses currently available.",
        formationOffensive: "Based on your offensive philosophy and high skill average, a 4-3-3 or 4-2-3-1 formation might be suitable.",
        strengthsOffensive: "Strengths: Ability to build offensive play, high individual skills, and advanced pressing.",
        weaknessesOffensive: "Potential weaknesses: There might be spaces behind the defense line, need for defensive balance.",
        formationDefensive: "Based on your defensive philosophy and good physical abilities average, a 4-4-2 or 5-3-2 formation might be suitable.",
        strengthsDefensive: "Strengths: Strong defensive organization, physical endurance ability, and defensive solidity.",
        weaknessesDefensive: "Potential weaknesses: May face difficulty in quick transition to attack, need for creative players upfront.",
        formationPossession: "Based on your possession philosophy and good tactical understanding average, a 4-3-3 or 4-1-4-1 formation might be suitable.",
        strengthsPossession: "Strengths: Ball control, building play from the back, and ability to dictate tempo.",
        weaknessesPossession: "Potential weaknesses: May be vulnerable to quick counter-attacks, need for high concentration throughout the match.",
        formationFormationBased: "You chose a formation-based philosophy. Please specify your preferred formation for deeper analysis.",
        strengthsFormationBased: "Strengths: Tactical flexibility and ability to adapt to opponents.",
        weaknessesFormationBased: "Potential weaknesses: May require more time for players to adapt to frequent formation changes.",
        formationGeneral: "No specific formation suggestion currently available. We can analyze deeper after selecting playing philosophy and having sufficient player data.",
        strengthsGeneral: "Strengths: Depend on team's average abilities.",
        weaknessesGeneral: "Weaknesses: Depend on team's average abilities.",
        programGenerationTitle: "Training Program Generation",
        annualProgram: "Annual Program",
        monthlyProgram: "Monthly Program",
        weeklyProgram: "Weekly Program",
        physicalProgram: "Physical Preparation Program",
        programOutputPlaceholder: "The generated training program will appear here.",
        generatingProgram: "Generating program...",
        programGenerationError: "Failed to generate training program. Please try again.",
        apiConnectionError: "Error occurred while connecting to the model:",
        printProgram: "Print Program (PDF)",
        printPdfNotAvailable: "PDF printing function is under development. You can copy the text manually.",
        aboutTitle: "About the Website",
        aboutText1: "This website is a comprehensive sports training management system for football, designed specifically for coaches. It provides advanced tools for creating customized training programs that suit team needs and preferred training style. Our goal is to simplify the planning and analysis process, helping coaches achieve maximum potential for their players and teams.",
        aboutText2: "The website includes features such as coach profile management, age group selection, training and match scheduling, playing philosophy determination, and comprehensive player management with detailed assessments of physical, tactical, and mental skills. It also provides advanced team analysis and plan suggestions, plus the ability to generate various training programs and print them.",
        contactTitle: "Contact Us",
        yourNameLabel: "Your Name:",
        yourNamePlaceholder: "Your full name",
        yourEmailLabel: "Your Email:",
        yourEmailPlaceholder: "example@example.com",
        yourMessageLabel: "Your Message:",
        yourMessagePlaceholder: "Write your message here...",
        sendMessage: "Send Message",
        footerText: "© 2025 Sports Training Management System. All rights reserved.",
        sunday: "Sunday",
        monday: "Monday",
        tuesday: "Tuesday",
        wednesday: "Wednesday",
        thursday: "Thursday",
        friday: "Friday",
        saturday: "Saturday",
        programFocusAnnual: "Comprehensive season planning, period division (preparation, competition, transition), and main objectives for each period.",
        programFocusMonthly: "Specific training objectives for the month, detailed exercises, and progress evaluation.",
        programFocusWeekly: "Daily training schedule, specific exercises, and training load distribution.",
        programFocusPhysical: "Comprehensive physical preparation program focusing on developing strength, speed, endurance, and flexibility."
    },
    
    fr: {
        pageTitle: "Système de Gestion d'Entraînement Sportif",
        appTitle: "Système de Gestion d'Entraînement",
        home: "Accueil",
        login: "Connexion",
        about: "À propos",
        contact: "Contactez-nous",
        userIdDisplay: "ID Utilisateur",
        userIdNotAvailable: "ID Utilisateur : Non disponible",
        welcomeTitle: "Bienvenue dans le Système de Gestion d'Entraînement Sportif",
        welcomeText: "Outils avancés pour les entraîneurs pour créer des programmes d'entraînement personnalisés en football.",
        getStarted: "Commencer",
        authModalTitle: "Connexion / Inscription",
        emailLabel: "Email :",
        emailPlaceholder: "Entrez votre email",
        passwordLabel: "Mot de passe :",
        passwordPlaceholder: "Entrez votre mot de passe",
        loginButton: "Se connecter",
        registerButton: "S'inscrire",
        logoutButton: "Se déconnecter",
        loginSuccess: "Connexion réussie !",
        registerSuccess: "Inscription réussie ! Vous pouvez maintenant vous connecter.",
        logoutSuccess: "Déconnexion réussie.",
        loginError: "Erreur de connexion :",
        registerError: "Erreur d'inscription :",
        logoutError: "Erreur de déconnexion :",
        coachProfileTitle: "Gestion du Profil d'Entraîneur",
        nameLabel: "Nom :",
        namePlaceholder: "Nom de l'entraîneur",
        ageLabel: "Âge :",
        agePlaceholder: "Âge de l'entraîneur",
        nationalityLabel: "Nationalité :",
        nationalityPlaceholder: "Nationalité de l'entraîneur",
        phoneLabel: "Numéro de téléphone :",
        phonePlaceholder: "Numéro de téléphone de l'entraîneur",
        coachLevelLabel: "Niveau d'entraînement :",
        selectLevel: "Sélectionner le niveau",
        saveCoachProfile: "Sauvegarder le profil d'entraîneur",
        saveCoachProfileSuccess: "Profil d'entraîneur sauvegardé avec succès !",
        saveCoachProfileError: "Erreur lors de la sauvegarde du profil d'entraîneur.",
        loginRequired: "Veuillez vous connecter d'abord pour sauvegarder les données.",
        ageGroupTitle: "Sélection de Groupe d'Âge",
        u15: "Moins de 15 ans",
        u17: "Moins de 17 ans",
        u19: "Moins de 19 ans",
        women: "Équipe Féminine",
        seniors: "Seniors",
        ageGroupInstructionsTitle: "Instructions du Groupe d'Âge :",
        ageGroupU15Instruction: "Instructions pour le groupe moins de 15 ans : Se concentrer sur les fondamentaux et développer les compétences individuelles.",
        ageGroupU17Instruction: "Instructions pour le groupe moins de 17 ans : Développer les aspects tactiques et la compréhension d'équipe.",
        ageGroupU19Instruction: "Instructions pour le groupe moins de 19 ans : Se concentrer sur la condition physique et l'endurance, affiner les compétences avancées.",
        ageGroupWomenInstruction: "Instructions pour l'équipe féminine : Programmes d'entraînement conçus pour répondre aux besoins physiques et tactiques des joueuses.",
        ageGroupSeniorsInstruction: "Instructions pour les seniors : Programmes d'entraînement de haut niveau axés sur la performance compétitive et les tactiques complexes.",
        saveAgeGroup: "Sauvegarder le groupe d'âge",
        saveAgeGroupSuccess: "Groupe d'âge sauvegardé :",
        saveAgeGroupError: "Erreur lors de la sauvegarde du groupe d'âge.",
        selectAgeGroupFirst: "Veuillez d'abord sélectionner un groupe d'âge.",
        scheduleManagementTitle: "Gestion des Horaires d'Entraînement et de Match",
        selectDay: "Sélectionner le jour",
        trainingTimePlaceholder: "Heure d'entraînement",
        matchTimePlaceholder: "Heure de match",
        addDaySchedule: "Ajouter un jour au planning",
        saveSchedule: "Sauvegarder le planning",
        saveScheduleSuccess: "Planning sauvegardé avec succès !",
        saveScheduleError: "Erreur lors de la sauvegarde du planning.",
        playingPhilosophyTitle: "Sélection de Philosophie de Jeu",
        offensive: "Offensive",
        defensive: "Défensive",
        possession: "Possession",
        formationbased: "Basée sur la formation",
        selectedPhilosophy: "Philosophie de jeu sélectionnée :",
        playerManagementTitle: "Gestion des Joueurs",
        playerNameLabel: "Nom du joueur :",
        playerNamePlaceholder: "Nom du joueur",
        skillCharacteristics: "Caractéristiques Techniques",
        passing: "Passes :",
        receiving: "Réception :",
        dribblingrun: "Course avec ballon :",
        dribblingskill: "Dribble :",
        heading: "Jeu de tête :",
        shooting: "Tir :",
        longpassing: "Passes longues :",
        ballcontrol: "Contrôle de balle :",
        twofooted: "Ambidextre :",
        finishingpressure: "Finition sous pression :",
        physicalAbilities: "Capacités Physiques",
        stamina: "Endurance :",
        fitness: "Condition physique :",
        physique: "Physique :",
        speed: "Vitesse :",
        strength: "Force :",
        balanceagility: "Équilibre et agilité :",
        tacticalUnderstanding: "Compréhension Tactique",
        gameintelligence: "Intelligence de jeu :",
        coachinstructions: "Suivi des instructions :",
        defensiveaggression: "Agressivité défensive :",
        offensivecontribution: "Contribution offensive :",
        positioning: "Positionnement :",
        readinggame: "Lecture du jeu :",
        teamworkpressing: "Travail d'équipe et pressing :",
        mentalPsychologicalTraits: "Traits Mentaux et Psychologiques",
        mentaltoughness: "Résistance mentale :",
        psychologicalstability: "Stabilité psychologique :",
        concentration: "Concentration :",
        selfconfidence: "Confiance en soi :",
        leadership: "Leadership :",
        handlingpressure: "Gestion de la pression :",
        motivationcompetitiveness: "Motivation et compétitivité :",
        addEditPlayer: "Ajouter / Modifier Joueur",
        addPlayerSuccess: "Joueur ajouté avec succès !",
        editPlayerSuccess: "Données du joueur mises à jour avec succès !",
        savePlayerError: "Erreur lors de la sauvegarde des données du joueur.",
        playerNameRequired: "Veuillez entrer le nom du joueur.",
        playersList: "Liste des Joueurs",
        tablePlayerName: "Nom",
        tableSkillAvg: "Technique (Moyenne)",
        tablePhysicalAvg: "Physique (Moyenne)",
        tableTacticalAvg: "Tactique (Moyenne)",
        tableMentalAvg: "Mental (Moyenne)",
        tableActions: "Actions",
        edit: "Modifier",
        delete: "Supprimer",
        confirmDeletePlayer: "Êtes-vous sûr de vouloir supprimer ce joueur ?",
        deletePlayerSuccess: "Joueur supprimé avec succès !",
        deletePlayerError: "Erreur lors de la suppression du joueur.",
        teamAnalysisTitle: "Analyse d'Équipe et Création de Plans",
        analyzeTeam: "Analyser l'équipe",
        noPlayersToAnalyze: "Aucun joueur à analyser. Veuillez d'abord ajouter des joueurs.",
        individualPlayerAnalysis: "Analyse Individuelle des Joueurs",
        playerType: "Type :",
        skillAvg: "Moyenne technique :",
        physicalAvg: "Moyenne physique :",
        tacticalAvg: "Moyenne tactique :",
        mentalAvg: "Moyenne mentale :",
        playerTypeSkillful: "Technique",
        playerTypePhysical: "Physique",
        playerTypeTactical: "Tactique",
        playerTypeMental: "Mental",
        playerTypeGeneral: "Général",
        teamCollectiveAnalysis: "Analyse Collective de l'Équipe",
        categoryAverages: "Moyennes par Catégorie",
        teamOverallAverages: "Moyennes Générales de l'Équipe",
        categorySkill: "Technique",
        categoryPhysical: "Physique",
        categoryTactical: "Tactique",
        categoryMental: "Mental",
        overallTeamAverage: "Moyenne générale de l'équipe :",
        suggestedFormations: "Formations Suggérées et Forces/Faiblesses",
        noFormationSuggestion: "Aucune suggestion de formation actuellement disponible.",
        noStrengthsWeaknesses: "Aucune force et faiblesse spécifique actuellement disponible.",
        formationOffensive: "Basé sur votre philosophie offensive et la moyenne technique élevée, une formation 4-3-3 ou 4-2-3-1 pourrait convenir.",
        strengthsOffensive: "Forces : Capacité à construire le jeu offensif, compétences individuelles élevées, et pressing avancé.",
        weaknessesOffensive: "Faiblesses potentielles : Il pourrait y avoir des espaces derrière la ligne de défense, besoin d'équilibre défensif.",
        formationDefensive: "Basé sur votre philosophie défensive et la bonne moyenne des capacités physiques, une formation 4-4-2 ou 5-3-2 pourrait convenir.",
        strengthsDefensive: "Forces : Organisation défensive solide, capacité d'endurance physique, et solidité défensive.",
        weaknessesDefensive: "Faiblesses potentielles : Peut avoir des difficultés dans la transition rapide vers l'attaque, besoin de joueurs créatifs devant.",
        formationPossession: "Basé sur votre philosophie de possession et la bonne moyenne de compréhension tactique, une formation 4-3-3 ou 4-1-4-1 pourrait convenir.",
        strengthsPossession: "Forces : Contrôle du ballon, construction du jeu depuis l'arrière, et capacité à dicter le tempo.",
        weaknessesPossession: "Faiblesses potentielles : Peut être vulnérable aux contre-attaques rapides, besoin de concentration élevée tout au long du match.",
        formationFormationBased: "Vous avez choisi une philosophie basée sur la formation. Veuillez spécifier votre formation préférée pour une analyse plus approfondie.",
        strengthsFormationBased: "Forces : Flexibilité tactique et capacité à s'adapter aux adversaires.",
        weaknessesFormationBased: "Faiblesses potentielles : Peut nécessiter plus de temps pour que les joueurs s'adaptent aux changements fréquents de formation.",
        formationGeneral: "Aucune suggestion de formation spécifique actuellement disponible. Nous pouvons analyser plus profondément après avoir sélectionné la philosophie de jeu et avoir suffisamment de données sur les joueurs.",
        strengthsGeneral: "Forces : Dépendent des capacités moyennes de l'équipe.",
        weaknessesGeneral: "Faiblesses : Dépendent des capacités moyennes de l'équipe.",
        programGenerationTitle: "Génération de Programmes d'Entraînement",
        annualProgram: "Programme Annuel",
        monthlyProgram: "Programme Mensuel",
        weeklyProgram: "Programme Hebdomadaire",
        physicalProgram: "Programme de Préparation Physique",
        programOutputPlaceholder: "Le programme d'entraînement généré apparaîtra ici.",
        generatingProgram: "Génération du programme...",
        programGenerationError: "Échec de la génération du programme d'entraînement. Veuillez réessayer.",
        apiConnectionError: "Erreur lors de la connexion au modèle :",
        printProgram: "Imprimer le programme (PDF)",
        printPdfNotAvailable: "La fonction d'impression PDF est en cours de développement. Vous pouvez copier le texte manuellement.",
        aboutTitle: "À propos du site web",
        aboutText1: "Ce site web est un système complet de gestion d'entraînement sportif pour le football, conçu spécifiquement pour les entraîneurs. Il fournit des outils avancés pour créer des programmes d'entraînement personnalisés qui conviennent aux besoins de l'équipe et au style d'entraînement préféré. Notre objectif est de simplifier le processus de planification et d'analyse, aidant les entraîneurs à atteindre le potentiel maximum de leurs joueurs et équipes.",
        aboutText2: "Le site web comprend des fonctionnalités telles que la gestion du profil d'entraîneur, la sélection de groupes d'âge, la planification des entraînements et des matchs, la détermination de la philosophie de jeu, et la gestion complète des joueurs avec des évaluations détaillées des compétences physiques, tactiques et mentales. Il fournit également une analyse avancée de l'équipe et des suggestions de plans, plus la capacité de générer divers programmes d'entraînement et de les imprimer.",
        contactTitle: "Contactez-nous",
        yourNameLabel: "Votre nom :",
        yourNamePlaceholder: "Votre nom complet",
        yourEmailLabel: "Votre email :",
        yourEmailPlaceholder: "exemple@exemple.com",
        yourMessageLabel: "Votre message :",
        yourMessagePlaceholder: "Écrivez votre message ici...",
        sendMessage: "Envoyer le message",
        footerText: "© 2025 Système de Gestion d'Entraînement Sportif. Tous droits réservés.",
        sunday: "Dimanche",
        monday: "Lundi",
        tuesday: "Mardi",
        wednesday: "Mercredi",
        thursday: "Jeudi",
        friday: "Vendredi",
        saturday: "Samedi",
        programFocusAnnual: "Planification complète de la saison, division des périodes (préparation, compétition, transition), et objectifs principaux pour chaque période.",
        programFocusMonthly: "Objectifs d'entraînement spécifiques pour le mois, exercices détaillés, et évaluation des progrès.",
        programFocusWeekly: "Planning quotidien d'entraînement, exercices spécifiques, et distribution de la charge d'entraînement.",
        programFocusPhysical: "Programme complet de préparation physique axé sur le développement de la force, de la vitesse, de l'endurance et de la flexibilité."
    }
};

